language: r
sudo: required
warnings_are_errors: false
  
r_github_packages:
  - hadley/testthat
  - hadley/httr
  - hadley/readr
  - hadley/dplyr
  - klutometis/roxygen
  - jimhester/covr
  - yihui/knitr

notifications:
  email:
    on_success: never
    on_failure: always
    
after_success:
  - Rscript -e 'library(covr);coveralls()'
